Support missing codomain maps
glencoesoftware/omero-ms-image-region pull request #120
Opened 2023-01-05 16:51 UTC by kkoz

Supplementary to #119 . To shorten URLs for images with large numbers of channels, we'd like to be able to omit the codomain chain information for channels which are inactive. In #119 we suggested assuming that any channel not specified in the URL is considered inactive. We propose here to do the same thing with codomain maps. Previously, we assumed that the first n codomain maps corresponded to the first n channels - if 2 maps were provided they were assigned to channels 1 and 2. With the new changes, the maps are applied to the corresponding provided channels. E.g. If the image has 6 channels and 1,3, and 5 are active, the `c` part of the query string would be like `1|0:255$FF0000,3|0:255$00FF00,5|0:255$0000FF`. The client would either provide no map query, or provide 3 elements in `maps`, like  `[{"inverted":{"enabled":false},"quantization":{"family":"polynomial","coefficient":1.2}},{"inverted":{"enabled":false}},{"inverted":{"enabled":false}}]`. The first map would be applied to channel 1, the second to channel 3, and the third to channel 5, since those were the channels specified in `c`. Note that all provided channels should specify a codomain map, including ones marked inactive with a negative index.
### Testing
With or without the change, the request:
http://localhost:8080/webgateway/render_image_region/15757/0/0/?m=c&z=1&t=1&format=jpeg&maps=[{%22inverted%22:{%22enabled%22:false}},{%22inverted%22:{%22enabled%22:false},%22quantization%22:{%22family%22:%22polynomial%22,%22coefficient%22:1.4}},{%22inverted%22:{%22enabled%22:false}}]&c=-1|0:255$FF0000,2|0:255$00FF00,3|0:255$0000FF&tile=0,0,0,512,512
Should be the same as, with the change:
http://localhost:8080/webgateway/render_image_region/15757/0/0/?m=c&z=1&t=1&format=jpeg&maps=[{%22inverted%22:{%22enabled%22:false},%22quantization%22:{%22family%22:%22polynomial%22,%22coefficient%22:1.4}},{%22inverted%22:{%22enabled%22:false}}]&c=2|0:255$00FF00,3|0:255$0000FF&tile=0,0,0,512,512

2023-01-06 08:37 UTC, knabar commented
@kkoz I would strengthen the specification (which I think is what you're already implemented):

The first map would be applied to channel 1, the second to channel 3, and the third to channel 5, since those were the channels specified in c, **and in that order**. Note that all provided channels **must** specify a codomain map, including ones marked inactive with a negative index.

2023-01-06 12:44 UTC, sbesson commented
My understanding is that the upstream specification for these requests is defined in https://omero.readthedocs.io/en/stable/developers/Web/WebGateway.html#rendering-settings. As can be seen, the definition of the codomain map parameters is minimal and does not include much information regarding the contract and the relationship with specified channels.

For testing, I have been using the following image from IDR (https://idr.openmicroscopy.org/webclient/img_detail/10501752/) which has 60 channels with 8 of them being activated by default.

The following URLs are all equivalent representations of the default view

- all channels and maps specified explicitly https://idr.openmicroscopy.org/webgateway/render_image_region/10501752/0/0/?c=1|0:10$00FF00,-2|0:9.612$00FF00,-3|6.741:80.371$0000FF,-4|24.672:115.32$FF0000,-5|5.019:70.393$00FF00,-6|0:1263.418$0000FF,-7|0:12.77$FF0000,8|0:10$FF0000,-9|0:200.046$0000FF,-10|0:41.758$FF0000,-11|0:66.187$00FF00,-12|0:9.618$0000FF,13|0:10$0000FF,-14|0:16.535$00FF00,15|0:34.953$0000FF,-16|0:14.228$FF0000,-17|0:9.129$00FF00,-18|0:320.713$0000FF,-19|0:8.195$FF0000,-20|0:9.91$00FF00,-21|0:247.238$0000FF,-22|0:78.065$FF0000,-23|0:36.065$00FF00,-24|0:1793.681$0000FF,-25|0:9.72$FF0000,26|0:10$FFFF00,-27|0:12.475$0000FF,-28|0:105.464$FF0000,-29|0:240.476$00FF00,30|0:10$00FFFF,-31|0:33.465$FF0000,-32|0:84.92$00FF00,-33|0:28.315$0000FF,34|0:10$FF00FF,-35|0:12.745$00FF00,-36|0:134.274$0000FF,-37|0:12.848$FF0000,-38|0:36.504$00FF00,-39|0:9.255$0000FF,-40|0:41.373$FF0000,41|0:10$FFFFFF,-42|0:167.164$0000FF,-43|0:223.096$FF0000,-44|0:366.447$00FF00,-45|0:16.401$0000FF,-46|0:10.226$FF0000,-47|0:11.285$00FF00,-48|0:10.977$0000FF,-49|0:12.707$FF0000,-50|5555.561:7036.383$00FF00&maps=[{"inverted":{"enabled":false}},{},{},{},{},{},{},{"inverted":{"enabled":false}},{},{},{},{},{"inverted":{"enabled":false}},{},{"inverted":{"enabled":false}},{},{},{},{},{},{},{},{},{},{},{"inverted":{"enabled":false}},{},{},{},{"inverted":{"enabled":false}},{},{},{},{"inverted":{"enabled":false}},{},{},{},{},{},{},{"inverted":{"enabled":false}},{},{},{},{},{},{},{},{},{}]&q=0.9&tile=0,0,0,464,494
- only channels specified explicitly https://idr.openmicroscopy.org/webgateway/render_image_region/10501752/0/0/?c=1|0:10$00FF00,-2|0:9.612$00FF00,-3|6.741:80.371$0000FF,-4|24.672:115.32$FF0000,-5|5.019:70.393$00FF00,-6|0:1263.418$0000FF,-7|0:12.77$FF0000,8|0:10$FF0000,-9|0:200.046$0000FF,-10|0:41.758$FF0000,-11|0:66.187$00FF00,-12|0:9.618$0000FF,13|0:10$0000FF,-14|0:16.535$00FF00,15|0:34.953$0000FF,-16|0:14.228$FF0000,-17|0:9.129$00FF00,-18|0:320.713$0000FF,-19|0:8.195$FF0000,-20|0:9.91$00FF00,-21|0:247.238$0000FF,-22|0:78.065$FF0000,-23|0:36.065$00FF00,-24|0:1793.681$0000FF,-25|0:9.72$FF0000,26|0:10$FFFF00,-27|0:12.475$0000FF,-28|0:105.464$FF0000,-29|0:240.476$00FF00,30|0:10$00FFFF,-31|0:33.465$FF0000,-32|0:84.92$00FF00,-33|0:28.315$0000FF,34|0:10$FF00FF,-35|0:12.745$00FF00,-36|0:134.274$0000FF,-37|0:12.848$FF0000,-38|0:36.504$00FF00,-39|0:9.255$0000FF,-40|0:41.373$FF0000,41|0:10$FFFFFF,-42|0:167.164$0000FF,-43|0:223.096$FF0000,-44|0:366.447$00FF00,-45|0:16.401$0000FF,-46|0:10.226$FF0000,-47|0:11.285$00FF00,-48|0:10.977$0000FF,-49|0:12.707$FF0000,-50|5555.561:7036.383$00FF00&tile=0,0,0,464,494
- only active channels specified explicitly https://idr.openmicroscopy.org/webgateway/render_image_region/10501752/0/0/?c=1|0:10$00FF00,8|0:10$FF0000,13|0:10$0000FF,15|0:34.953$0000FF,26|0:10$FFFF00,30|0:10$00FFFF,34|0:10$FF00FF,41|0:10$FFFFFF&tile=0,0,0,464,494
- only tile specified https://idr.openmicroscopy.org/webgateway/render_image_region/10501752/0/0/?tile=0,0,0,464,494

The following URLs actively modify the codomain map for one of the active channels

-  custom map for the first specified channel (channel 1)
   https://idr.openmicroscopy.org/webgateway/render_image_region/10501752/0/0/?c=1|0:10$00FF00,8|0:10$FF0000,13|0:10$0000FF,15|0:34.953$0000FF,26|0:10$FFFF00,30|0:10$00FFFF,34|0:10$FF00FF,41|0:10$FFFFFF&maps=[{"inverted":{"enabled":true},"quantization":{"family":"polynomial","coefficient":1.2}}]&tile=0,0,0,464,494
- custom map for the last specified channel (channel 41)
  https://idr.openmicroscopy.org/webgateway/render_image_region/10501752/0/0/?c=1|0:10$00FF00,8|0:10$FF0000,13|0:10$0000FF,15|0:34.953$0000FF,26|0:10$FFFF00,30|0:10$00FFFF,34|0:10$FF00FF,41|0:10$FFFFFF&maps=[{},{},{},{},{},{},{},{"inverted":{"enabled":true},"quantization":{"family":"polynomial","coefficient":1.2}}]&tile=0,0,0,464,494
-  custom map for the last specified channel (channel 34)
    https://idr.openmicroscopy.org/webgateway/render_image_region/10501752/0/0/?c=1|0:10$00FF00,8|0:10$FF0000,13|0:10$0000FF,15|0:34.953$0000FF,26|0:10$FFFF00,30|0:10$00FFFF,41|0:10$FFFFFF,34|0:10$FF00FF&maps=[{},{},{},{},{},{},{},{"inverted":{"enabled":true},"quantization":{"family":"polynomial","coefficient":1.2}}]&tile=0,0,0,464,494

The following URL returns the default view as the index of the codomain map is associated with an inactive channel
https://idr.openmicroscopy.org/webgateway/render_image_region/10501752/0/0/?c=1|0:10$00FF00,-2,-3,-4,-5,-6,-7,8|0:10$FF0000,13|0:10$0000FF,15|0:34.953$0000FF,26|0:10$FFFF00,30|0:10$00FFFF,34|0:10$FF00FF,41|0:10$FFFFFF&maps=[{},{"inverted":{"enabled":true},"quantization":{"family":"polynomial","coefficient":1.2}}]&tile=0,0,0,464,494

The following URL returns the default view as the index of the codomain map is larger than the number of specified channels
https://idr.openmicroscopy.org/webgateway/render_image_region/10501752/0/0/?c=1|0:10$00FF00,8|0:10$FF0000,13|0:10$0000FF,15|0:34.953$0000FF,26|0:10$FFFF00,30|0:10$00FFFF,34|0:10$FF00FF,41|0:10$FFFFFF&maps=[{},{},{},{},{},{},{},{},{},{"inverted":{"enabled":true},"quantization":{"family":"polynomial","coefficient":1.2}}]&tile=0,0,0,464,494

The behavior of the default OMERO.web `render_image_region` largely matches the specification defined above. Possibly the only point of divergence is the requirement that maps and channels _must_ have identical length where OMERO.web is more lenient and behaves as follows:
- if the number of maps is smaller than the number of specified channels, the missing maps are assumed to be empty
- if the number of maps is larger than the number of specified channels, the extra maps are ignored

2023-01-18 12:20 UTC, sbesson requested changes
Using the reference  multi-channel image with 8 active channels, the `render_image_region` endpoint was tested against a series of quantization settings for the 8th channel (white).

- default `?m=c&c=1|0:10$00FF00,8|0:10$FF0000,13|0:10$0000FF,15|0:34.953$0000FF,26|0:10$FFFF00,30|0:10$00FFFF,34|0:10$FF00FF,41|0:10$FFFFFF&tile=0,0,0,464,494`
![default](https://user-images.githubusercontent.com/1355463/213164922-93d57982-2917-4034-be27-2127c982aadd.jpeg)

- polynomial `?m=c&c=1|0:10$00FF00,8|0:10$FF0000,13|0:10$0000FF,15|0:34.953$0000FF,26|0:10$FFFF00,30|0:10$00FFFF,34|0:10$FF00FF,41|0:10$FFFFFF&maps=[{},{},{},{},{},{},{},{"inverted":{"enabled":false},"quantization":{"family":"polynomial","coefficient":2}}]&tile=0,0,0,464,494`
![polynomial](https://user-images.githubusercontent.com/1355463/213164961-20abb816-013a-4456-b422-9d3d3ce0aeab.jpeg)


- exponential `?m=c&c=1|0:10$00FF00,8|0:10$FF0000,13|0:10$0000FF,15|0:34.953$0000FF,26|0:10$FFFF00,30|0:10$00FFFF,34|0:10$FF00FF,41|0:10$FFFFFF&maps=[{},{},{},{},{},{},{},{"inverted":{"enabled":false},"quantization":{"family":"exponential","coefficient":2}}]&tile=0,0,0,464,494`

![exponential](https://user-images.githubusercontent.com/1355463/213164981-6d114ee3-7312-479d-8bbf-0fc9a589b6b4.jpeg)

- logarithmic `?m=c&c=1|0:10$00FF00,8|0:10$FF0000,13|0:10$0000FF,15|0:34.953$0000FF,26|0:10$FFFF00,30|0:10$00FFFF,34|0:10$FF00FF,41|0:10$FFFFFF&maps=[{},{},{},{},{},{},{},{"inverted":{"enabled":false},"quantization":{"family":"logarithmic","coefficient":2}}]&tile=0,0,0,464,494`
![logarithmic](https://user-images.githubusercontent.com/1355463/213165006-ac67c1f8-6311-4dcf-9b20-e1907d130a9c.jpeg)


- inverted `?m=c&c=1|0:10$00FF00,8|0:10$FF0000,13|0:10$0000FF,15|0:34.953$0000FF,26|0:10$FFFF00,30|0:10$00FFFF,34|0:10$FF00FF,41|0:10$FFFFFF&maps=[{},{},{},{},{},{},{},{"inverted":{"enabled":true},"quantization":{"family":"linear","coefficient":2}}]&tile=0,0,0,464,494`
![inverted](https://user-images.githubusercontent.com/1355463/213165041-82837c1d-e7ce-43a0-8cfa-8d35d65465be.jpeg)


All the rendered regions are in agreement with the view of https://idr.openmicroscopy.org/webclient/img_detail/10501752/ when adjusting the quantization settings via the UI. Interestingly, this testing exposed a discrepancy with the behavior of the OMERO.web `render_image_region` endpoint where the codomain maps seem to be mapped to the absolute channel index rather than the index of the channels as defined by the `c=` parameter.

The current documentation lacks specifics about how `maps` should be interpreted and clients like OMERO.iviewer are internally generating URLs which include all channels in `c=` so this scenario is not really exposed unless you construct the URL manually.

Since the micro-service enforces the specification of a `c` parameter, I completely agree with the spirit of this PR which enforces that the `maps` parameter must be directly related to `c`. The current OMERO.web behavior seems counter-intuitive and adds unnecessary complexity to the semantics of the `maps` parameters especially in scenarios where one would like to specify a sparse number of channels/codomain maps for highly multiplexed images of 80+ images. I suspect this is an oversight of the original implementation but we should open the discussion with the OME team and align the expectations of this parameters before integrating this. This is also a great occasion to clarify the missing bits of the documentation for consumers.

The expansion of the unit tests cover a wide range of scenarios with different quantization parameters, sparse channels as well mixtures of quantization families. 

Can a few tests be amended to cover the scenario where `{}` is passed rather than `{"reverse": {"enabled": false}}` to skip quantization parameters for a given channel as this should be the shortest form?
How easy is it to add tests covering the channel inversion scenario?

2023-01-20 18:02 UTC, sbesson approved these changes
All good from the code and tests perspective. I assume the next step is to engage the discussion at the omero-documentation/omero-web levels to propagate the specification updates proposed here?

2023-03-03 10:20 UTC, merged