Use end instead of write
glencoesoftware/omero-ms-image-region pull request #133
Opened 2023-10-18 14:31 UTC by kkoz

When errors were received from Verticles, they were handled by the `handleResultFailed` function. Previously, even though these called `setStatusCode` on the response, the response codes were always 200. We determined that this had something to do with the call to `response.write`. If instead the message is supplied via `response.end`, the status code we supplied is used. To prevent getting exceptions later in the code (where we call `response.end` if the response is not closed - calling `end` twice throws), we now call `close` in `handleResultFailed`.

2023-10-18 16:09 UTC, knabar commented
Makes sense to me - is this change deployed somewhere for testing?

2023-10-18 16:09 UTC, knabar commented
Also cc: @emilroz

2023-10-18 16:18 UTC, sbesson commented
I was planning to review it locally first thing tomorrow morning but I could also schedule its deployment onto `us-demo` if that was useful.
Possibly also use the opportunity to upgrade the server and any other components to the state of Fuchsia

2023-10-19 15:16 UTC, sbesson requested changes
One outstanding question about the conditional handling if `t` is not a `ReplyException` (as a side question: under which conditions this would happen?).

Otherwise, based on preliminary testing, errors like `Cannot find Label Metadata` or `Cannot find Image` that were previously returning 200 status codes are now returning 404 error codes. I'll try to make a list of a few endpoints which should be tested

2023-10-19 20:51 UTC, kkoz commented on src/main/java/com/glencoesoftware/omero/ms/image/region/ImageRegionMicroserviceVerticle.java
> +                if (statusCode < 200 || statusCode > 599) {
Yes you're correct - I thought there would be a way to reach the inside of that block without being a ReplyException but I forgot that the `statusCode` is manually set to 404 before.

2023-10-19 20:54 UTC, kkoz commented on src/main/java/com/glencoesoftware/omero/ms/image/region/ImageRegionMicroserviceVerticle.java
> +                if (statusCode < 200 || statusCode > 599) {
In response to your question about exceptions other than `ReplyException` - I don't think so but I'd need to try some stuff out.

2023-10-20 17:46 UTC, knabar approved these changes
Testing on `v2-demo-dev`, I now get a `404` status code when requesting metadata for non-existent label image IDs

2023-10-24 10:58 UTC, sbesson approved these changes
Retested with a few endpoints `render_image_region`, `histogram_json` using various combinations of invalid request (non-existing image IDs, request parameters outside the supported ranges).

Without this change, the micro-service would return a 200 error code with a message. With this change, a  404 error code is being now returned to the user.

I would be inclined to get this out immediately as a patch release of the micro-service @knabar @kkoz

2023-10-24 14:22 UTC, chris-allan requested changes
As structured, I'm pretty sure this will not work and breaks what it was designed to fix: `-1` status codes.

2023-10-24 16:03 UTC, chris-allan approved these changes

2023-10-25 10:14 UTC, sbesson approved these changes
The last commit implements the changes discussed yesterday with @kkoz @chris-allan and @muhanadz.
This has been deployed and restested in a few scenarios to assess the different failure behavrios:

- in the most common failure use case e.g. when trying to access a non-existing resource e.g. `webgateway/render_image_region/<invalid_id>/...`, the micro-service generates an HTTP response with a 404 status code using the default status message (`Not Found`) and a reponse body providing more context on the nature of the error e.g. `Cannot find Image:<invalid_id>`
- the easiest approach to test the logic resetting the status code outside the [200,599] range was to force the request to time-out. One synthetic way to do this is to import a [test image](https://bio-formats.readthedocs.io/en/stable/developers/generating-test-images.html) with `sleepOpenBytes=30000`. Any call to e.g. `render_image_region` will internally time-out, and the micro-service will generate an HTTP response with an error code 500 using the default status message (`Internal Server Error`) where the body contains more details of the underlying issue `Timed out after waiting 30000(ms) for a reply. address: __vertx.reply.106, repliedAddress: omero.render_image_region`. Inspecting the micro-service logs confirms a `-1` failure code was correctly turned into a 500 error code:

  ```
  2023-10-25 09:53:42,255 [vert.x-eventloop-thread-9] ERROR c.g.o.m.i.r.ImageRegionMicroserviceVerticle - Unexpected failureCode -1 resetting to 500
  io.vertx.core.eventbus.ReplyException: Timed out after waiting 30000(ms) for a reply. address: __vertx.reply.107, repliedAddress: omero.render_image_region
  ```
- as discussed internally, the conditions for generating a failure which cause is not a `ReplyException` are still not clear and the `else` statement could not be directly verified. With the additional comments, keeping it in the code base if the most defensive approach to handle all possible scenarios.

2023-10-25 10:16 UTC, merged