Zarr tests
glencoesoftware/omero-ms-image-region pull request #79
Opened 2021-06-02 19:30 UTC by kkoz

First pass at ZarrPixelBufferTests

2021-06-07 23:10 UTC, chris-allan commented
@kkoz: Green as of 0ba571f27ed6e57660f1e28c14b1d230cc5ebef6. You can relax the logging now as you desire.

2021-06-09 11:55 UTC, chris-allan requested changes
Did you have problems with the float vs. double and autoboxing comparisons in the test cases?

2021-06-09 11:55 UTC, chris-allan commented on src/main/java/com/glencoesoftware/omero/ms/image/region/ZarrPixelBuffer.java
> +        } catch(DimensionsOutOfBoundsException e) {
Formatting

2021-06-09 11:55 UTC, chris-allan commented on src/test/java/com/glencoesoftware/omero/ms/image/region/ZarrPixelBufferTest.java
> +package com.glencoesoftware.omero.ms.image.region;
Needs a file header.

2021-06-09 12:35 UTC, kkoz commented
@chris-allan It wasn't really the autoboxing. Just that the JUnit assertEquals method for primitive floating point numbers requires a delta to be provided, so instead I converted to the objects types for comparison.

2021-06-09 15:25 UTC, chris-allan commented
:+1:

In b31e6b0350ebd521d421232a6473555b5d28039f I've just simplified that a little so that there's no autoboxing confusion created by setting no delta. Effectively they're the same thing.

Let me know if you want to do anything else after the commits I've added and if not I'll get this merged.

2021-06-09 17:04 UTC, kkoz commented
I think it's ready to be merged.

2021-06-09 17:15 UTC, merged